
const staticStatements = {
   LoginText: 'Login to your account',
   ReigsterText: 'Hey There!',
   createText: 'Create an account',
   Login: ' Login',
   number: '+91 8360312345',
   projectTitle: 'VibCare',
   divisiontitle: 'Please enter divisons',
   divisons: 'Pin Code*',
   Home: 'Home',
   Categories: 'Categories',
   TherapeuticSegment: 'Therapeutic Segment',
   Offers: 'Offers',
   MyOrders: 'My Orders',
   OrderDetails: 'Order Details',
   signUpWithFB: 'Sign in with Facebook',
   // signUp: 'Sign Up',
   TermsAndConditions: 'Terms And Conditions',
   PrivacyPolicy: 'Privacy Policy',
   LogOut: 'Log out',
   signIn: ' Register',
   Verify: 'Verify',
   Next: 'Proceed KYC',
   Skip: 'Skip',
   Resend: 'Resend',
   Submit: 'Submit',
   FirstName: 'First Name',
   LastName: 'Last name',
   phoneNumber: 'Phone Number',
   countryCode: '+91',
   OTPTitle: 'Verify Phone',
   title: 'Title',
   PromotionalMaterial: 'Promotional Material',
   OTPSent: 'One time password (OTP) has been\nsent to your mobile number',
   enterOTPText: 'Enter your registered phone number\nto receive OTP',
   emailText: 'Email',
   passwordText: 'Password',
   forgotPassword: 'Forgot Password?',
   SetupAccount: 'KYC',
   KYC: "Process",
   BasicDetails: 'Basic Details',
   ShippingandBillingAddress: 'Shipping and Billing Address',
   CompanyName: 'Company / Firm Name*',
   GSTNumber: 'Division',

   Gstnumber: 'GST Number',
   LicenseNo: 'License No',
   UploadFile: 'Upload File',
   GSTNo: 'GST No.',
   AadhaarNo: 'Aadhaar No.',
   PanNo: 'Pan No',
   DateofBirth: 'Date of Birth*',
   DateofAnniversary: 'Date of Anniversary',
   Email: 'Email Address',

   AddressLine1: 'Address Line 1',
   Pincode: 'Pincode',
   AddressLine2: 'Address Line 2',
   poweredbyText: 'Powered by',
   form20B: "Form 20B",
   filter: "Filter",
   noData: "No Data found",
   requestBulkRate: "Request Bulk Rate",
   requestProduct: 'Request A Product',
   notification: 'Notification',
   requestNewMolecule: "Request New Molecule",
   ptrptscalculator: 'PTR & PTS Calculator',
   incentiveprogram: 'Incentive Program',
   newrequestBulkmolecule: "Request New Molecule",
   // assignDisplayText: "Assign Display",
   // profileText: "Profile",
   // displayProfileText: "Display Profile",
   // assignDisplayProfileText: "Assign Display Profile",
   // createNewDisplayProfile: "Create New Display Profile",

   // createDisplayText: "Create Display",
   // deviceNameText: "Device Name",
   // location: "Location",
   // mapLocation: "Map Location",

   // nextText: "Next",
   // refreshFrequencyText: "Refresh Frequency",
   // displayTimeText: "Display Time",
   // batchCountText: "Batch Count",
   // displayOrientationText: "Display Orientation",
}

const validationTexts = {

   phoneRequireText: "Phone number is required.",
   passwordRequiredText: "Password is required.",
   EmailRequiredText: "Email is required.",
   OTPRequireText: 'OTP is required',
   gstRequireText: "GST number is required.",
   address1RequireText: "Address line 1 is required.",
   address2RequireText: "Address line 2 is required.",
   pincodeRequireText: "Pincode is required.",
   pincodeValidation: 'Please enter valid pincode',
   pincodeValidRequireText: "Please enter valid pincode",
   stateRequireText: 'Please select state',
   cityRequiretext: 'Please select city',
   OTPLengthValidation: 'Please enter valid OTP',
   enterValidEmailText: "Please enter valid email.",
   enterValidPasswordText: "Please enter 6 digit password",
   phoneValid: "Please enter valid phone number",
   gstValid: "Please enter valid GST number",
   EmailText:'Please enter email',
   emailValid:'Please enter valid email',
   Uploadvalidation: 'Please upload your documents',
   selectDeviceIdText: "Please select device id",
   enterNameText: "Please enter Name",
   enterCompanyNameText: "Please enter Company / Firm Name",
   enterPincode: "Please enter Pin Code",
   enterPincodeText: 'Please enter valid pin code number ',
   selectDisplayTypeText: "Please select display type",
   selectOsText: "Please select operating system",
   selectIndoorText: "Please select indoor status",
   enterTitle: "Please enter address",
   enterMessage: "Please select state",
   enterCity: 'Please select city',
   enterPincode: 'Please enter pincode',
   licenseNoText: 'Please enter license number',
   upLoadFileText: 'Please select file',
   adhaarNoText: 'Please enter valid aadhaar number',
   adhaarNo: 'Please enter aadhaar number',
   panNo: 'Please enter pan number',
   panNoText: 'Please enter valid PAN number',
   choosenDateText: 'Please select date',
   FirstnameText: 'Please enter first name',
   LastnameText: 'Please enter last name',

    

   enterRefreshFrequecy: "Please enter Refresh Frequency",
   enterDisplayTime: "Please enter Display Time",
   enterBatchCount: "Please enter Batch Count",
   selectDeviceOrientation: "Please select Display Orientation",
   kyc_rejected: "Your kyc has been rejected,please submit again",
   kyc_notDone: "You have not completed your kyc,please complete your kyc first.",
   kyc_notApprovedYet: "Your kyc is not approved yet.",
   mrp: 'MRP'
}

const staticArray = {

}

export const ConstantsText = {
   welcome: 'Pick Your Interests',
   appName: 'Leva',
   openGallery: 'Gallery',
   openCamera: 'Take Photo',
   Cancel: 'Cancel',

   serverErrorMessage: 'Server Error',
   noNetworkAlert: 'No Internet Connection',
   requestTimeoutMessage: 'request Timeout',
   netTitle: 'Network',
   networkErrorMessage: 'network Error',
   somethingWrongText: 'Something went wrong..',
   logOutMessage: 'Are you sure you want to logout?',
}

const staticText = {
   ...staticArray,
   ...staticStatements,
   ...validationTexts,
   ...ConstantsText,
}
export default staticText;